apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-mirrors"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  {{- range $val := .Values.mirrors }}
  {{ $val.name }}.yaml: |
    {{- toYaml $val | nindent 4 }}
  {{- end }}
 
