name: Publish Docker image as release
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to gchr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: server build and push
        uses: docker/build-push-action@v2
        with:
          context: image
          file: image/server.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mirror-server:latest
            ghcr.io/${{ github.repository_owner }}/mirror-server:release-${{ env.IMAGE_VERSION }}
      - name: syncer build and push
        uses: docker/build-push-action@v2
        with:
          context: image
          file: image/syncer.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mirror-syncer:latest
            ghcr.io/${{ github.repository_owner }}/mirror-syncer:release-${{ env.IMAGE_VERSION }}

