name: Build Docker image
on: [push, pull_request]
jobs:
  build:
    name: Build Docker image to gchr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "${GITHUB_REF}" | grep "refs/tags" >/dev/null && echo "IMAGE_VERSION=${GITHUB_REF#refs/*/v}" || echo "IMAGE_VERSION=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: server build and push
        uses: docker/build-push-action@v2
        with:
          context: image
          file: image/server.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/mirror-server:latest
            ghcr.io/${{ github.repository_owner }}/mirror-server:tag-${{ env.IMAGE_VERSION }}
      - name: syncer build and push
        uses: docker/build-push-action@v2
        with:
          context: image
          file: image/syncer.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/mirror-server:latest
            ghcr.io/${{ github.repository_owner }}/mirror-server:tag-${{ env.IMAGE_VERSION }}

